export const ADD_TODO = 'ADD_TODO';
export const ACTIVATE_TODO = 'ACTIVATE_TODO';
export const DEACTIVATE_TODO = 'DEACTIVATE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const FETCHING_TODO_REQUEST = 'FETCHING_TODO_REQUEST';
export const FETCHING_TODO_SUCCESS = 'FETCHING_TODO_SUCCESS';
export const FETCHING_TODO_FAILURE = 'FETCHING_TODO_FAILURE';
